apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: saf-sample-dubbo-apollo-web-prod
    inc-app: saf-sample-dubbo-apollo-web
  name: saf-sample-dubbo-apollo-web-prod
  namespace: inc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: saf-sample-dubbo-apollo-web-prod
